
# This file is automatically generated, you probably don't want to edit this

AnovaOptions <- R6::R6Class(
    "AnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            fixedFactors = NULL,
            wlsWeights = NULL,
            modelTerms = NULL,
            contrasts = NULL,
            descPlotsHAxis = NULL,
            descPlotsSepLines = NULL,
            descPlotsSepPlots = NULL,
            postHoc = NULL,
            corrTukey = FALSE,
            corrScheffe = FALSE,
            corrBonf = FALSE,
            corrHolm = FALSE,
            compMain = FALSE,
            compMainCorr = "none",
            descStats = FALSE,
            homo = FALSE,
            qq = FALSE,
            etaSq = FALSE,
            etaSqP = FALSE,
            omegaSq = FALSE,
            plotError = "ci",
            ciWidth = 95,
            ss = "3") {

            super$initialize(package='jmv', name='Anova')
        
            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..fixedFactors <- jmvcore::OptionVariables$new(
                "fixedFactors",
                fixedFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..wlsWeights <- jmvcore::OptionVariable$new(
                "wlsWeights",
                wlsWeights,
                default=NULL)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(fixedFactors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "none",
                                "deviation",
                                "simple",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial")))))
            private$..descPlotsHAxis <- jmvcore::OptionVariable$new(
                "descPlotsHAxis",
                descPlotsHAxis,
                default=NULL)
            private$..descPlotsSepLines <- jmvcore::OptionVariable$new(
                "descPlotsSepLines",
                descPlotsSepLines,
                default=NULL)
            private$..descPlotsSepPlots <- jmvcore::OptionVariable$new(
                "descPlotsSepPlots",
                descPlotsSepPlots,
                default=NULL)
            private$..postHoc <- jmvcore::OptionTerms$new(
                "postHoc",
                postHoc,
                default=NULL)
            private$..corrTukey <- jmvcore::OptionBool$new(
                "corrTukey",
                corrTukey,
                default=FALSE)
            private$..corrScheffe <- jmvcore::OptionBool$new(
                "corrScheffe",
                corrScheffe,
                default=FALSE)
            private$..corrBonf <- jmvcore::OptionBool$new(
                "corrBonf",
                corrBonf,
                default=FALSE)
            private$..corrHolm <- jmvcore::OptionBool$new(
                "corrHolm",
                corrHolm,
                default=FALSE)
            private$..compMain <- jmvcore::OptionBool$new(
                "compMain",
                compMain,
                default=FALSE)
            private$..compMainCorr <- jmvcore::OptionList$new(
                "compMainCorr",
                compMainCorr,
                options=list(
                    "none",
                    "tukey",
                    "bonferroni",
                    "scheffe",
                    "sidak"),
                default="none")
            private$..descStats <- jmvcore::OptionBool$new(
                "descStats",
                descStats,
                default=FALSE)
            private$..homo <- jmvcore::OptionBool$new(
                "homo",
                homo,
                default=FALSE)
            private$..qq <- jmvcore::OptionBool$new(
                "qq",
                qq,
                default=FALSE)
            private$..etaSq <- jmvcore::OptionBool$new(
                "etaSq",
                etaSq,
                default=FALSE)
            private$..etaSqP <- jmvcore::OptionBool$new(
                "etaSqP",
                etaSqP,
                default=FALSE)
            private$..omegaSq <- jmvcore::OptionBool$new(
                "omegaSq",
                omegaSq,
                default=FALSE)
            private$..plotError <- jmvcore::OptionList$new(
                "plotError",
                plotError,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..ss <- jmvcore::OptionList$new(
                "ss",
                ss,
                options=list(
                    "1",
                    "2",
                    "3"),
                default="3")
        
            self$.addOption(private$..dependent)
            self$.addOption(private$..fixedFactors)
            self$.addOption(private$..wlsWeights)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..descPlotsHAxis)
            self$.addOption(private$..descPlotsSepLines)
            self$.addOption(private$..descPlotsSepPlots)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..corrTukey)
            self$.addOption(private$..corrScheffe)
            self$.addOption(private$..corrBonf)
            self$.addOption(private$..corrHolm)
            self$.addOption(private$..compMain)
            self$.addOption(private$..compMainCorr)
            self$.addOption(private$..descStats)
            self$.addOption(private$..homo)
            self$.addOption(private$..qq)
            self$.addOption(private$..etaSq)
            self$.addOption(private$..etaSqP)
            self$.addOption(private$..omegaSq)
            self$.addOption(private$..plotError)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..ss)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        fixedFactors = function() private$..fixedFactors$value,
        wlsWeights = function() private$..wlsWeights$value,
        modelTerms = function() private$..modelTerms$value,
        contrasts = function() private$..contrasts$value,
        descPlotsHAxis = function() private$..descPlotsHAxis$value,
        descPlotsSepLines = function() private$..descPlotsSepLines$value,
        descPlotsSepPlots = function() private$..descPlotsSepPlots$value,
        postHoc = function() private$..postHoc$value,
        corrTukey = function() private$..corrTukey$value,
        corrScheffe = function() private$..corrScheffe$value,
        corrBonf = function() private$..corrBonf$value,
        corrHolm = function() private$..corrHolm$value,
        compMain = function() private$..compMain$value,
        compMainCorr = function() private$..compMainCorr$value,
        descStats = function() private$..descStats$value,
        homo = function() private$..homo$value,
        qq = function() private$..qq$value,
        etaSq = function() private$..etaSq$value,
        etaSqP = function() private$..etaSqP$value,
        omegaSq = function() private$..omegaSq$value,
        plotError = function() private$..plotError$value,
        ciWidth = function() private$..ciWidth$value,
        ss = function() private$..ss$value),
    private = list(
        ..dependent = NA,
        ..fixedFactors = NA,
        ..wlsWeights = NA,
        ..modelTerms = NA,
        ..contrasts = NA,
        ..descPlotsHAxis = NA,
        ..descPlotsSepLines = NA,
        ..descPlotsSepPlots = NA,
        ..postHoc = NA,
        ..corrTukey = NA,
        ..corrScheffe = NA,
        ..corrBonf = NA,
        ..corrHolm = NA,
        ..compMain = NA,
        ..compMainCorr = NA,
        ..descStats = NA,
        ..homo = NA,
        ..qq = NA,
        ..etaSq = NA,
        ..etaSqP = NA,
        ..omegaSq = NA,
        ..plotError = NA,
        ..ciWidth = NA,
        ..ss = NA)
)

AnovaBase <- R6::R6Class(
    "AnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="") {
            super$initialize(
                package = 'jmv',
                name = 'Anova',
                version = c(1,0,0),
                options = options,
                data = data,
                datasetId = datasetId,
                analysisId = analysisId)
        }))

Anova <- function(
    data,
    dependent,
    fixedFactors = NULL,
    wlsWeights = NULL,
    modelTerms = NULL,
    contrasts = NULL,
    descPlotsHAxis = NULL,
    descPlotsSepLines = NULL,
    descPlotsSepPlots = NULL,
    postHoc = NULL,
    corrTukey = FALSE,
    corrScheffe = FALSE,
    corrBonf = FALSE,
    corrHolm = FALSE,
    compMain = FALSE,
    compMainCorr = "none",
    descStats = FALSE,
    homo = FALSE,
    qq = FALSE,
    etaSq = FALSE,
    etaSqP = FALSE,
    omegaSq = FALSE,
    plotError = "ci",
    ciWidth = 95,
    ss = "3") {

    options <- AnovaOptions$new(
        dependent = dependent,
        fixedFactors = fixedFactors,
        wlsWeights = wlsWeights,
        modelTerms = modelTerms,
        contrasts = contrasts,
        descPlotsHAxis = descPlotsHAxis,
        descPlotsSepLines = descPlotsSepLines,
        descPlotsSepPlots = descPlotsSepPlots,
        postHoc = postHoc,
        corrTukey = corrTukey,
        corrScheffe = corrScheffe,
        corrBonf = corrBonf,
        corrHolm = corrHolm,
        compMain = compMain,
        compMainCorr = compMainCorr,
        descStats = descStats,
        homo = homo,
        qq = qq,
        etaSq = etaSq,
        etaSqP = etaSqP,
        omegaSq = omegaSq,
        plotError = plotError,
        ciWidth = ciWidth,
        ss = ss)

    analysis <- AnovaClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
