
# This file is automatically generated, you probably don't want to edit this

#' @rdname jamovi
#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
#' @export
anovaRMOptions <- R6::R6Class(
    "anovaRMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rm = list(
                list(label="RM Factor 1", levels=list(
                    "Level 1",
                    "Level 2"))),
            rmCells = NULL,
            bs = NULL,
            cov = NULL,
            rmTerms = NULL,
            bsTerms = NULL,
            ss = "3",
            effectSize = NULL,
            spherTests = FALSE,
            spherCorr = list(
                "none"),
            leveneTest = FALSE,
            contrasts = NULL,
            postHoc = NULL,
            postHocCorr = list(
                "tukey"),
            descPlotsHAxis = NULL,
            descPlotsSepLines = NULL,
            descPlotsSepPlots = NULL,
            descPlotsErrBar = "ci",
            descPlotsCIWidth = 95,
            dispDescStats = FALSE, ...) {

            super$initialize(
                package='jmv',
                name='anovaRM',
                requiresData=TRUE,
                ...)
        
            private$..rm <- jmvcore::OptionArray$new(
                "rm",
                rm,
                default=list(
                    list(label="RM Factor 1", levels=list(
                        "Level 1",
                        "Level 2"))),
                template=jmvcore::OptionGroup$new(
                    "rm",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..rmCells <- jmvcore::OptionArray$new(
                "rmCells",
                rmCells,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "rmCells",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "measure",
                            NULL),
                        jmvcore::OptionArray$new(
                            "cell",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "cell",
                                NULL)))))
            private$..bs <- jmvcore::OptionVariables$new(
                "bs",
                bs,
                suggested=list(
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..cov <- jmvcore::OptionVariables$new(
                "cov",
                cov,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..rmTerms <- jmvcore::OptionTerms$new(
                "rmTerms",
                rmTerms,
                default=NULL)
            private$..bsTerms <- jmvcore::OptionTerms$new(
                "bsTerms",
                bsTerms,
                default=NULL)
            private$..ss <- jmvcore::OptionList$new(
                "ss",
                ss,
                options=list(
                    "1",
                    "2",
                    "3"),
                default="3")
            private$..effectSize <- jmvcore::OptionNMXList$new(
                "effectSize",
                effectSize,
                options=list(
                    list(name="eta", title="\u03B7\u00B2"),
                    list(name="partEta", title="partial \u03B7\u00B2"),
                    list(name="omega", title="\u03C9\u00B2")))
            private$..spherTests <- jmvcore::OptionBool$new(
                "spherTests",
                spherTests,
                default=FALSE)
            private$..spherCorr <- jmvcore::OptionNMXList$new(
                "spherCorr",
                spherCorr,
                options=list(
                    list(name="none", title="None"),
                    list(name="GG", title="Greenhouse-Geisser"),
                    list(name="HF", title="Huynh-Feldt")),
                default=list(
                    "none"))
            private$..leveneTest <- jmvcore::OptionBool$new(
                "leveneTest",
                leveneTest,
                default=FALSE)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(bs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "none",
                                "deviation",
                                "simple",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial")))))
            private$..postHoc <- jmvcore::OptionArray$new(
                "postHoc",
                postHoc,
                template=jmvcore::OptionArray$new(
                    "postHoc",
                    NULL,
                    template=jmvcore::OptionString$new(
                        "postHoc",
                        NULL)),
                default=NULL)
            private$..postHocCorr <- jmvcore::OptionNMXList$new(
                "postHocCorr",
                postHocCorr,
                options=list(
                    list(name="tukey", title="Tukey"),
                    list(name="scheffe", title="Scheffe"),
                    list(name="bonf", title="Bonferroni"),
                    list(name="holm", title="Holm")),
                default=list(
                    "tukey"))
            private$..descPlotsHAxis <- jmvcore::OptionVariable$new(
                "descPlotsHAxis",
                descPlotsHAxis,
                default=NULL)
            private$..descPlotsSepLines <- jmvcore::OptionVariable$new(
                "descPlotsSepLines",
                descPlotsSepLines,
                default=NULL)
            private$..descPlotsSepPlots <- jmvcore::OptionVariable$new(
                "descPlotsSepPlots",
                descPlotsSepPlots,
                default=NULL)
            private$..descPlotsErrBar <- jmvcore::OptionList$new(
                "descPlotsErrBar",
                descPlotsErrBar,
                options=list(
                    "none",
                    "ci",
                    "se"),
                default="ci")
            private$..descPlotsCIWidth <- jmvcore::OptionNumber$new(
                "descPlotsCIWidth",
                descPlotsCIWidth,
                min=50,
                max=99.9,
                default=95)
            private$..dispDescStats <- jmvcore::OptionBool$new(
                "dispDescStats",
                dispDescStats,
                default=FALSE)
        
            self$.addOption(private$..rm)
            self$.addOption(private$..rmCells)
            self$.addOption(private$..bs)
            self$.addOption(private$..cov)
            self$.addOption(private$..rmTerms)
            self$.addOption(private$..bsTerms)
            self$.addOption(private$..ss)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..spherTests)
            self$.addOption(private$..spherCorr)
            self$.addOption(private$..leveneTest)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..postHocCorr)
            self$.addOption(private$..descPlotsHAxis)
            self$.addOption(private$..descPlotsSepLines)
            self$.addOption(private$..descPlotsSepPlots)
            self$.addOption(private$..descPlotsErrBar)
            self$.addOption(private$..descPlotsCIWidth)
            self$.addOption(private$..dispDescStats)
        }),
    active = list(
        rm = function() private$..rm$value,
        rmCells = function() private$..rmCells$value,
        bs = function() private$..bs$value,
        cov = function() private$..cov$value,
        rmTerms = function() private$..rmTerms$value,
        bsTerms = function() private$..bsTerms$value,
        ss = function() private$..ss$value,
        effectSize = function() private$..effectSize$value,
        spherTests = function() private$..spherTests$value,
        spherCorr = function() private$..spherCorr$value,
        leveneTest = function() private$..leveneTest$value,
        contrasts = function() private$..contrasts$value,
        postHoc = function() private$..postHoc$value,
        postHocCorr = function() private$..postHocCorr$value,
        descPlotsHAxis = function() private$..descPlotsHAxis$value,
        descPlotsSepLines = function() private$..descPlotsSepLines$value,
        descPlotsSepPlots = function() private$..descPlotsSepPlots$value,
        descPlotsErrBar = function() private$..descPlotsErrBar$value,
        descPlotsCIWidth = function() private$..descPlotsCIWidth$value,
        dispDescStats = function() private$..dispDescStats$value),
    private = list(
        ..rm = NA,
        ..rmCells = NA,
        ..bs = NA,
        ..cov = NA,
        ..rmTerms = NA,
        ..bsTerms = NA,
        ..ss = NA,
        ..effectSize = NA,
        ..spherTests = NA,
        ..spherCorr = NA,
        ..leveneTest = NA,
        ..contrasts = NA,
        ..postHoc = NA,
        ..postHocCorr = NA,
        ..descPlotsHAxis = NA,
        ..descPlotsSepLines = NA,
        ..descPlotsSepPlots = NA,
        ..descPlotsErrBar = NA,
        ..descPlotsCIWidth = NA,
        ..dispDescStats = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
anovaRMResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        rmTable = function() private$..rmTable,
        bsTable = function() private$..bsTable,
        assump = function() private$..assump,
        contrasts = function() private$..contrasts,
        postHoc = function() private$..postHoc,
        descPlot = function() private$..descPlot,
        descPlots = function() private$..descPlots),
    private = list(
        ..rmTable = NA,
        ..bsTable = NA,
        ..assump = NA,
        ..contrasts = NA,
        ..postHoc = NA,
        ..descPlot = NA,
        ..descPlots = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Repeated Measures ANOVA")
            private$..rmTable <- jmvcore::Table$new(
                options=options,
                name="rmTable",
                title="Within Subjects Effects",
                clearWith=list(
                    "dependent",
                    "ss",
                    "rmCells",
                    "rmcModelTerms",
                    "bscModelTerms",
                    "bs",
                    "rm",
                    "cov",
                    "rmTerms",
                    "bsTerms"),
                columns=list(
                    list(`name`="name", `title`="", `content`=".", `type`="text"),
                    list(`name`="correction[none]", `title`="Sphericity Correction", `content`="None", `visible`="(spherCorr:none && (spherCorr:GG || spherCorr:HF))"),
                    list(`name`="ss[none]", `title`="Sum of Squares", `type`="number", `visible`="(spherCorr:none)"),
                    list(`name`="df[none]", `title`="df", `type`="integer", `visible`="(spherCorr:none)"),
                    list(`name`="ms[none]", `title`="Mean Square", `type`="number", `visible`="(spherCorr:none)"),
                    list(`name`="F[none]", `title`="F", `type`="number", `visible`="(spherCorr:none)"),
                    list(`name`="p[none]", `title`="p", `type`="number", `format`="zto,pvalue", `visible`="(spherCorr:none)"),
                    list(`name`="eta[none]", `title`="\u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:eta && spherCorr:none)"),
                    list(`name`="partEta[none]", `title`="partial \u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:partEta && spherCorr:none)"),
                    list(`name`="omega[none]", `title`="\u03C9\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:omega && spherCorr:none)"),
                    list(`name`="correction[GG]", `title`="Sphericity Correction", `content`="Greenhouse-Geisser", `visible`="(spherCorr:GG)"),
                    list(`name`="ss[GG]", `title`="Sum of Squares", `type`="number", `visible`="(spherCorr:GG)"),
                    list(`name`="df[GG]", `title`="df", `type`="number", `visible`="(spherCorr:GG)"),
                    list(`name`="ms[GG]", `title`="Mean Square", `type`="number", `visible`="(spherCorr:GG)"),
                    list(`name`="F[GG]", `title`="F", `type`="number", `visible`="(spherCorr:GG)"),
                    list(`name`="p[GG]", `title`="p", `type`="number", `format`="zto,pvalue", `visible`="(spherCorr:GG)"),
                    list(`name`="eta[GG]", `title`="\u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:eta && spherCorr:GG)"),
                    list(`name`="partEta[GG]", `title`="partial \u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:partEta && spherCorr:GG)"),
                    list(`name`="omega[GG]", `title`="\u03C9\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:omega && spherCorr:GG)"),
                    list(`name`="correction[HF]", `title`="Sphericity Correction", `content`="Huynh-Feldt", `visible`="(spherCorr:HF)"),
                    list(`name`="ss[HF]", `title`="Sum of Squares", `type`="number", `visible`="(spherCorr:HF)"),
                    list(`name`="df[HF]", `title`="df", `type`="number", `visible`="(spherCorr:HF)"),
                    list(`name`="ms[HF]", `title`="Mean Square", `type`="number", `visible`="(spherCorr:HF)"),
                    list(`name`="F[HF]", `title`="F", `type`="number", `visible`="(spherCorr:HF)"),
                    list(`name`="p[HF]", `title`="p", `type`="number", `format`="zto,pvalue", `visible`="(spherCorr:HF)"),
                    list(`name`="eta[HF]", `title`="\u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:eta && spherCorr:HF)"),
                    list(`name`="partEta[HF]", `title`="partial \u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:partEta && spherCorr:HF)"),
                    list(`name`="omega[HF]", `title`="\u03C9\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:omega && spherCorr:HF)")))
            private$..bsTable <- jmvcore::Table$new(
                options=options,
                name="bsTable",
                title="Between Subjects Effects",
                clearWith=list(
                    "dependent",
                    "ss",
                    "rmCells",
                    "rmcModelTerms",
                    "bscModelTerms",
                    "bs",
                    "rm",
                    "cov",
                    "rmTerms",
                    "bsTerms"),
                columns=list(
                    list(`name`="name", `title`="", `content`=".", `type`="text"),
                    list(`name`="ss", `title`="Sum of Squares", `type`="number"),
                    list(`name`="df", `title`="df", `type`="integer"),
                    list(`name`="ms", `title`="Mean Square", `type`="number"),
                    list(`name`="F", `title`="F", `type`="number"),
                    list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"),
                    list(`name`="eta", `title`="\u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:eta)"),
                    list(`name`="partEta", `title`="partial \u03B7\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:partEta)"),
                    list(`name`="omega", `title`="\u03C9\u00B2", `type`="number", `format`="zto", `visible`="(effectSize:omega)")))
            private$..assump <- R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    spherTable = function() private$..spherTable,
                    leveneTable = function() private$..leveneTable),
                private = list(
                    ..spherTable = NA,
                    ..leveneTable = NA),
                public=list(
                    initialize=function(options) {
                        super$initialize(options=options, name="assump", title="Assumptions")
                        private$..spherTable <- jmvcore::Table$new(
                            options=options,
                            name="spherTable",
                            title="Tests of Sphericity",
                            visible="(spherTests)",
                            clearWith=list(
                                "dependent",
                                "ss",
                                "rmCells",
                                "rmcModelTerms",
                                "bscModelTerms",
                                "bs",
                                "rm",
                                "cov",
                                "rmTerms",
                                "bsTerms"),
                            columns=list(
                                list(`name`="name", `title`="", `type`="text"),
                                list(`name`="mauch", `title`="Mauchly's W", `type`="number"),
                                list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"),
                                list(`name`="gg", `title`="Greenhouse-Geisser \u03B5", `type`="number"),
                                list(`name`="hf", `title`="Huynh-Feldt \u03B5", `type`="number")))
                        private$..leveneTable <- jmvcore::Table$new(
                            options=options,
                            name="leveneTable",
                            title="Equality of variances test (Levene's)",
                            visible="(leveneTest)",
                            clearWith=list(
                                "bs",
                                "rmCells",
                                "cov"),
                            columns=list(
                                list(`name`="name", `title`="", `type`="text"),
                                list(`name`="F", `type`="number"),
                                list(`name`="df1", `type`="integer"),
                                list(`name`="df2", `type`="integer"),
                                list(`name`="p", `type`="number", `format`="zto,pvalue")))
                        self$add(private$..spherTable)
                        self$add(private$..leveneTable)}))$new(options=options)
            private$..contrasts <- jmvcore::Array$new(
                options=options,
                name="contrasts",
                title="Contrasts",
                items=0,
                visible="(contrasts)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Contrasts - $key",
                    rows=0,
                    columns=list(
                        list(`name`="contrast", `title`="", `type`="text"),
                        list(`name`="est", `title`="Estimate", `type`="number"),
                        list(`name`="se", `title`="SE", `type`="number"),
                        list(`name`="t", `type`="number"),
                        list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"))))
            private$..postHoc <- jmvcore::Array$new(
                options=options,
                name="postHoc",
                title="Post Hoc Tests",
                items="(postHoc)",
                template=jmvcore::Table$new(
                    options=options,
                    title="",
                    clearWith=list(
                        "dependent",
                        "ss",
                        "rmCells",
                        "rmcModelTerms",
                        "bscModelTerms",
                        "bs",
                        "rm",
                        "cov",
                        "rmTerms",
                        "bsTerms")))
            private$..descPlot <- jmvcore::Image$new(
                options=options,
                name="descPlot",
                title="Descriptive Plot",
                visible="(descPlotsHAxis)",
                width=500,
                height=300,
                renderInitFun=".descPlot",
                renderFun=".descPlot",
                clearWith=list(
                    "descPlotsHAxis",
                    "descPlotsSepLines",
                    "descPlotsSepPlots",
                    "rm",
                    "descPlotsErrBar",
                    "descPlotsCIWidth"))
            private$..descPlots <- jmvcore::Array$new(
                options=options,
                name="descPlots",
                title="Descriptive Plots",
                visible="(descPlotsSepPlots)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    renderInitFun=".descPlot",
                    renderFun=".descPlot",
                    clearWith=list(
                        "descPlotsHAxis",
                        "descPlotsSepLines",
                        "descPlotsSepPlots",
                        "rm",
                        "descPlotsErrBar",
                        "descPlotsCIWidth")))
            self$add(private$..rmTable)
            self$add(private$..bsTable)
            self$add(private$..assump)
            self$add(private$..contrasts)
            self$add(private$..postHoc)
            self$add(private$..descPlot)
            self$add(private$..descPlots)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
anovaRMBase <- R6::R6Class(
    "anovaRMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmv',
                name = 'anovaRM',
                version = c(1,0,0),
                options = options,
                results = anovaRMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' Repeated Measures ANOVA
#'
#' 
#' @param data the data as a data frame
#' @param rm a list of lists, where each list describes the \code{label} (as a 
#'   string) and the \code{levels} (as vector of strings) of a particular 
#'   repeated measures factor 
#' @param rmCells a list of lists, where each list decribes a repeated measure 
#'   (as a string) from \code{data} defined as \code{measure} and the particular 
#'   combination of levels from \code{rm} that it belongs to (as a vector of 
#'   strings) defined as \code{cell} 
#' @param bs a vector of strings naming the between subjects factors from 
#'   \code{data} 
#' @param cov a vector of strings naming the covariates from \code{data}. 
#'   Variables must be numeric 
#' @param rmTerms a list of character vectors describing the repeated measures 
#'   terms to go into the model 
#' @param bsTerms a list of character vectors describing the between subjects 
#'   terms to go into the model 
#' @param ss \code{'1'}, \code{'2'} or \code{'3'} (default) - the sum of 
#'   squares to use 
#' @param effectSize a vector of strings indicating which effect size is to be 
#'   computed. One (or more) of \code{'eta'}, \code{'partEta'}, or 
#'   \code{`omega`} can be chosen 
#' @param spherTests TRUE or FALSE (default), perform sphericity tests
#' @param spherCorr a vector of strings indicating whether any sphericity 
#'   corrections are to be computed. One (or more) of \code{'none'}, \code{'GG'} 
#'   (Greenhouse-Geisser), or \code{`HF`} (Huynh-Feldt) can be chosen 
#' @param leveneTest TRUE or FALSE (default), test for equality of variances 
#'   (i.e., Levene's test) 
#' @param contrasts .
#' @param postHoc a list of character vectors describing the post-hoc tests 
#'   that need to be computed 
#' @param postHocCorr a vector of strings indicating which p-value correction 
#'   should be used for the post-hoc tests. One (or more) of \code{'tukey'} 
#'   (default), \code{'scheffe'}, \code{'bonf'} (Bonferroni), or \code{'holm'} 
#'   can be chosen 
#' @param descPlotsHAxis a string naming the variable placed on the horizontal 
#'   axis of the plot 
#' @param descPlotsSepLines a string naming the variable represented as 
#'   separate lines on the plot 
#' @param descPlotsSepPlots a string naming the variable to separate over to 
#'   form multiple plots 
#' @param descPlotsErrBar \code ('none'), \code{'ci'} (default), or 
#'   \code{'se'}. Use no error bars, confidence intervals, or standard errors on 
#'   the plots 
#' @param descPlotsCIWidth a number between 50 and 99.9 (default: 95) 
#'   specifying the confidence interval width 
#' @param dispDescStats Display Descriptive statistics 
#' @export
anovaRM <- function(
    data,
    rm = list(
                list(label="RM Factor 1", levels=list(
                    "Level 1",
                    "Level 2"))),
    rmCells = NULL,
    bs = NULL,
    cov = NULL,
    rmTerms = NULL,
    bsTerms = NULL,
    ss = "3",
    effectSize,
    spherTests = FALSE,
    spherCorr = list(
                "none"),
    leveneTest = FALSE,
    contrasts = NULL,
    postHoc = NULL,
    postHocCorr = list(
                "tukey"),
    descPlotsHAxis = NULL,
    descPlotsSepLines = NULL,
    descPlotsSepPlots = NULL,
    descPlotsErrBar = "ci",
    descPlotsCIWidth = 95,
    dispDescStats = FALSE) {

    options <- anovaRMOptions$new(
        rm = rm,
        rmCells = rmCells,
        bs = bs,
        cov = cov,
        rmTerms = rmTerms,
        bsTerms = bsTerms,
        ss = ss,
        effectSize = effectSize,
        spherTests = spherTests,
        spherCorr = spherCorr,
        leveneTest = leveneTest,
        contrasts = contrasts,
        postHoc = postHoc,
        postHocCorr = postHocCorr,
        descPlotsHAxis = descPlotsHAxis,
        descPlotsSepLines = descPlotsSepLines,
        descPlotsSepPlots = descPlotsSepPlots,
        descPlotsErrBar = descPlotsErrBar,
        descPlotsCIWidth = descPlotsCIWidth,
        dispDescStats = dispDescStats)

    results <- anovaRMResults$new(
        options = options)

    analysis <- anovaRMClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
