
# This file is automatically generated, you probably don't want to edit this

AnovaRMOptions <- R6::R6Class(
    "AnovaRMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rm = list(
                list(label="RM Factor 1", levels=list(
                    "Level 1",
                    "Level 2"))),
            rmCells = NULL,
            bs = NULL,
            cov = NULL,
            rmTerms = NULL,
            bsTerms = NULL,
            ss = "3",
            spherTests = FALSE,
            spherCorrs = FALSE,
            spherCorrNone = FALSE,
            spherCorrGreenGsser = FALSE,
            spherCorrHuyFdt = FALSE,
            homoTests = FALSE,
            contrasts = NULL,
            postHoc = NULL,
            corrTukey = FALSE,
            corrScheffe = FALSE,
            corrBonf = FALSE,
            corrHolm = FALSE,
            descPlotsHAxis = NULL,
            descPlotsSepLines = NULL,
            descPlotsSepPlots = NULL,
            dispErrBars = FALSE,
            errBarDef = "ci",
            ciWidth = 95,
            dispDescStats = FALSE,
            estEffSize = FALSE,
            effSizeN2 = FALSE,
            partEffSizeN2 = FALSE,
            effSizeW2 = FALSE, ...) {

            super$initialize(package='jmv', name='AnovaRM', ...)
        
            private$..rm <- jmvcore::OptionArray$new(
                "rm",
                rm,
                default=list(
                    list(label="RM Factor 1", levels=list(
                        "Level 1",
                        "Level 2"))),
                template=jmvcore::OptionGroup$new(
                    "rm",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..rmCells <- jmvcore::OptionArray$new(
                "rmCells",
                rmCells,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "rmCells",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "measure",
                            NULL),
                        jmvcore::OptionArray$new(
                            "cell",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "cell",
                                NULL)))))
            private$..bs <- jmvcore::OptionVariables$new(
                "bs",
                bs,
                suggested=list(
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..cov <- jmvcore::OptionVariables$new(
                "cov",
                cov,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..rmTerms <- jmvcore::OptionTerms$new(
                "rmTerms",
                rmTerms,
                default=NULL)
            private$..bsTerms <- jmvcore::OptionTerms$new(
                "bsTerms",
                bsTerms,
                default=NULL)
            private$..ss <- jmvcore::OptionList$new(
                "ss",
                ss,
                options=list(
                    "1",
                    "2",
                    "3"),
                default="3")
            private$..spherTests <- jmvcore::OptionBool$new(
                "spherTests",
                spherTests,
                default=FALSE)
            private$..spherCorrs <- jmvcore::OptionBool$new(
                "spherCorrs",
                spherCorrs,
                default=FALSE)
            private$..spherCorrNone <- jmvcore::OptionBool$new(
                "spherCorrNone",
                spherCorrNone,
                default=FALSE)
            private$..spherCorrGreenGsser <- jmvcore::OptionBool$new(
                "spherCorrGreenGsser",
                spherCorrGreenGsser,
                default=FALSE)
            private$..spherCorrHuyFdt <- jmvcore::OptionBool$new(
                "spherCorrHuyFdt",
                spherCorrHuyFdt,
                default=FALSE)
            private$..homoTests <- jmvcore::OptionBool$new(
                "homoTests",
                homoTests,
                default=FALSE)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(bs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "none",
                                "deviation",
                                "simple",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial")))))
            private$..postHoc <- jmvcore::OptionVariables$new(
                "postHoc",
                postHoc,
                default=NULL)
            private$..corrTukey <- jmvcore::OptionBool$new(
                "corrTukey",
                corrTukey,
                default=FALSE)
            private$..corrScheffe <- jmvcore::OptionBool$new(
                "corrScheffe",
                corrScheffe,
                default=FALSE)
            private$..corrBonf <- jmvcore::OptionBool$new(
                "corrBonf",
                corrBonf,
                default=FALSE)
            private$..corrHolm <- jmvcore::OptionBool$new(
                "corrHolm",
                corrHolm,
                default=FALSE)
            private$..descPlotsHAxis <- jmvcore::OptionVariable$new(
                "descPlotsHAxis",
                descPlotsHAxis,
                default=NULL)
            private$..descPlotsSepLines <- jmvcore::OptionVariable$new(
                "descPlotsSepLines",
                descPlotsSepLines,
                default=NULL)
            private$..descPlotsSepPlots <- jmvcore::OptionVariable$new(
                "descPlotsSepPlots",
                descPlotsSepPlots,
                default=NULL)
            private$..dispErrBars <- jmvcore::OptionBool$new(
                "dispErrBars",
                dispErrBars,
                default=FALSE)
            private$..errBarDef <- jmvcore::OptionList$new(
                "errBarDef",
                errBarDef,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..dispDescStats <- jmvcore::OptionBool$new(
                "dispDescStats",
                dispDescStats,
                default=FALSE)
            private$..estEffSize <- jmvcore::OptionBool$new(
                "estEffSize",
                estEffSize,
                default=FALSE)
            private$..effSizeN2 <- jmvcore::OptionBool$new(
                "effSizeN2",
                effSizeN2,
                default=FALSE)
            private$..partEffSizeN2 <- jmvcore::OptionBool$new(
                "partEffSizeN2",
                partEffSizeN2,
                default=FALSE)
            private$..effSizeW2 <- jmvcore::OptionBool$new(
                "effSizeW2",
                effSizeW2,
                default=FALSE)
        
            self$.addOption(private$..rm)
            self$.addOption(private$..rmCells)
            self$.addOption(private$..bs)
            self$.addOption(private$..cov)
            self$.addOption(private$..rmTerms)
            self$.addOption(private$..bsTerms)
            self$.addOption(private$..ss)
            self$.addOption(private$..spherTests)
            self$.addOption(private$..spherCorrs)
            self$.addOption(private$..spherCorrNone)
            self$.addOption(private$..spherCorrGreenGsser)
            self$.addOption(private$..spherCorrHuyFdt)
            self$.addOption(private$..homoTests)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..corrTukey)
            self$.addOption(private$..corrScheffe)
            self$.addOption(private$..corrBonf)
            self$.addOption(private$..corrHolm)
            self$.addOption(private$..descPlotsHAxis)
            self$.addOption(private$..descPlotsSepLines)
            self$.addOption(private$..descPlotsSepPlots)
            self$.addOption(private$..dispErrBars)
            self$.addOption(private$..errBarDef)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..dispDescStats)
            self$.addOption(private$..estEffSize)
            self$.addOption(private$..effSizeN2)
            self$.addOption(private$..partEffSizeN2)
            self$.addOption(private$..effSizeW2)
        }),
    active = list(
        rm = function() private$..rm$value,
        rmCells = function() private$..rmCells$value,
        bs = function() private$..bs$value,
        cov = function() private$..cov$value,
        rmTerms = function() private$..rmTerms$value,
        bsTerms = function() private$..bsTerms$value,
        ss = function() private$..ss$value,
        spherTests = function() private$..spherTests$value,
        spherCorrs = function() private$..spherCorrs$value,
        spherCorrNone = function() private$..spherCorrNone$value,
        spherCorrGreenGsser = function() private$..spherCorrGreenGsser$value,
        spherCorrHuyFdt = function() private$..spherCorrHuyFdt$value,
        homoTests = function() private$..homoTests$value,
        contrasts = function() private$..contrasts$value,
        postHoc = function() private$..postHoc$value,
        corrTukey = function() private$..corrTukey$value,
        corrScheffe = function() private$..corrScheffe$value,
        corrBonf = function() private$..corrBonf$value,
        corrHolm = function() private$..corrHolm$value,
        descPlotsHAxis = function() private$..descPlotsHAxis$value,
        descPlotsSepLines = function() private$..descPlotsSepLines$value,
        descPlotsSepPlots = function() private$..descPlotsSepPlots$value,
        dispErrBars = function() private$..dispErrBars$value,
        errBarDef = function() private$..errBarDef$value,
        ciWidth = function() private$..ciWidth$value,
        dispDescStats = function() private$..dispDescStats$value,
        estEffSize = function() private$..estEffSize$value,
        effSizeN2 = function() private$..effSizeN2$value,
        partEffSizeN2 = function() private$..partEffSizeN2$value,
        effSizeW2 = function() private$..effSizeW2$value),
    private = list(
        ..rm = NA,
        ..rmCells = NA,
        ..bs = NA,
        ..cov = NA,
        ..rmTerms = NA,
        ..bsTerms = NA,
        ..ss = NA,
        ..spherTests = NA,
        ..spherCorrs = NA,
        ..spherCorrNone = NA,
        ..spherCorrGreenGsser = NA,
        ..spherCorrHuyFdt = NA,
        ..homoTests = NA,
        ..contrasts = NA,
        ..postHoc = NA,
        ..corrTukey = NA,
        ..corrScheffe = NA,
        ..corrBonf = NA,
        ..corrHolm = NA,
        ..descPlotsHAxis = NA,
        ..descPlotsSepLines = NA,
        ..descPlotsSepPlots = NA,
        ..dispErrBars = NA,
        ..errBarDef = NA,
        ..ciWidth = NA,
        ..dispDescStats = NA,
        ..estEffSize = NA,
        ..effSizeN2 = NA,
        ..partEffSizeN2 = NA,
        ..effSizeW2 = NA)
)

AnovaRMResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        rmTable = function() private$..rmTable,
        bsTable = function() private$..bsTable,
        assump = function() private$..assump,
        contrasts = function() private$..contrasts,
        postHoc = function() private$..postHoc,
        descPlot = function() private$..descPlot),
    private = list(
        ..rmTable = NA,
        ..bsTable = NA,
        ..assump = NA,
        ..contrasts = NA,
        ..postHoc = NA,
        ..descPlot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Repeated Measures ANOVA")
            private$..rmTable <- jmvcore::Table$new(
                options=options,
                name="rmTable",
                title="Within Subjects Effects",
                clearWith=list(
                    "dependent",
                    "ss",
                    "rmCells",
                    "rmcModelTerms",
                    "bscModelTerms",
                    "bs",
                    "rm",
                    "cov",
                    "rmTerms",
                    "bsTerms"),
                columns=list(
                    list(`name`="name", `title`="", `content`=".", `type`="text"),
                    list(`name`="ss", `title`="Sum of Squares", `type`="number"),
                    list(`name`="df", `title`="df", `type`="integer"),
                    list(`name`="ms", `title`="Mean Square", `type`="number"),
                    list(`name`="F", `title`="F", `type`="number"),
                    list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"),
                    list(`name`="eta", `title`="η²", `type`="number", `format`="number", `visible`="(effSizeN2)"),
                    list(`name`="partEta", `title`="partial η²", `type`="number", `format`="number", `visible`="(partEffSizeN2)"),
                    list(`name`="omega", `title`="ω²", `type`="number", `format`="number", `visible`="(effSizeW2)")))
            private$..bsTable <- jmvcore::Table$new(
                options=options,
                name="bsTable",
                title="Between Subjects Effects",
                clearWith=list(
                    "dependent",
                    "ss",
                    "rmCells",
                    "rmcModelTerms",
                    "bscModelTerms",
                    "bs",
                    "rm",
                    "cov",
                    "rmTerms",
                    "bsTerms"),
                columns=list(
                    list(`name`="name", `title`="", `content`=".", `type`="text"),
                    list(`name`="ss", `title`="Sum of Squares", `type`="number"),
                    list(`name`="df", `title`="df", `type`="integer"),
                    list(`name`="ms", `title`="Mean Square", `type`="number"),
                    list(`name`="F", `title`="F", `type`="number"),
                    list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"),
                    list(`name`="eta", `title`="η²", `type`="number", `format`="number", `visible`="(effSizeN2)"),
                    list(`name`="partEta", `title`="partial η²", `type`="number", `format`="number", `visible`="(partEffSizeN2)"),
                    list(`name`="omega", `title`="ω²", `type`="number", `format`="number", `visible`="(effSizeW2)")))
            private$..assump <- R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    spher = function() private$..spher,
                    eqVar = function() private$..eqVar),
                private = list(
                    ..spher = NA,
                    ..eqVar = NA),
                public=list(
                    initialize=function(options) {
                        super$initialize(options=options, name="assump", title="Assumptions")
                        private$..spher <- jmvcore::Table$new(
                            options=options,
                            name="spher",
                            title="Tests of Sphericity",
                            visible="(spherTests)",
                            columns=list(
                                list(`name`="name", `title`=""),
                                list(`name`="mauch", `title`="Mauchly's W", `type`="number"),
                                list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"),
                                list(`name`="gg", `title`="Greenhouse-Geisser ε", `type`="number"),
                                list(`name`="hf", `title`="Huynh-Feldt ε", `type`="number")))
                        private$..eqVar <- jmvcore::Table$new(
                            options=options,
                            name="eqVar",
                            title="Test for Equality of Variances (Levene's)",
                            visible=FALSE,
                            rows=1,
                            columns=list(
                                list(`name`="F", `type`="number"),
                                list(`name`="df1", `type`="integer"),
                                list(`name`="df2", `type`="integer"),
                                list(`name`="p", `type`="number", `format`="zto,pvalue")))
                        self$add(private$..spher)
                        self$add(private$..eqVar)}))$new(options=options)
            private$..contrasts <- jmvcore::Array$new(
                options=options,
                name="contrasts",
                title="Contrasts",
                items=0,
                visible="(contrasts)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Contrasts - $key",
                    rows=0,
                    columns=list(
                        list(`name`="contrast", `title`="", `type`="text"),
                        list(`name`="est", `title`="Estimate", `type`="number"),
                        list(`name`="se", `title`="SE", `type`="number"),
                        list(`name`="t", `type`="number"),
                        list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"))))
            private$..postHoc <- jmvcore::Array$new(
                options=options,
                name="postHoc",
                title="Post Hoc Tests",
                items="(postHoc)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Post Hoc Comparisons - $key",
                    columns=list(
                        list(`name`="var1", `title`="", `type`="text"),
                        list(`name`="var2", `title`="", `type`="text"),
                        list(`name`="md", `title`="Mean Difference", `type`="number"),
                        list(`name`="se", `title`="SE", `type`="number"),
                        list(`name`="t", `title`="t", `type`="number"),
                        list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue"),
                        list(`name`="ptukey", `title`="p<sub>tukey</p>", `visible`="(corrTukey)", `type`="number", `format`="zto,pvalue"),
                        list(`name`="pscheffe", `title`="p<sub>scheffe</p>", `visible`="(corrScheffe)", `type`="number", `format`="zto,pvalue"),
                        list(`name`="pbonferroni", `title`="p<sub>bonferoni</p>", `visible`="(corrBonf)", `type`="number", `format`="zto,pvalue"),
                        list(`name`="pholm", `title`="p<sub>holm</p>", `visible`="(corrHolm)", `type`="number", `format`="zto,pvalue"))))
            private$..descPlot <- jmvcore::Image$new(
                options=options,
                name="descPlot",
                title="Descriptive Plot",
                visible="(descPlotsHAxis)",
                width=500,
                height=300,
                renderInitFun=".descPlot",
                renderFun=".descPlot",
                clearWith=list(
                    "descPlotsHAxis",
                    "descPlotsSepLines",
                    "descPlotsSepPlots",
                    "rm",
                    "dispErrBars",
                    "errBarDef",
                    "ciWidth"))
            self$add(private$..rmTable)
            self$add(private$..bsTable)
            self$add(private$..assump)
            self$add(private$..contrasts)
            self$add(private$..postHoc)
            self$add(private$..descPlot)}))

AnovaRMBase <- R6::R6Class(
    "AnovaRMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmv',
                name = 'AnovaRM',
                version = c(1,0,0),
                options = options,
                results = AnovaRMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

AnovaRM <- function(
    data,
    rm = list(
                list(label="RM Factor 1", levels=list(
                    "Level 1",
                    "Level 2"))),
    rmCells = NULL,
    bs = NULL,
    cov = NULL,
    rmTerms = NULL,
    bsTerms = NULL,
    ss = "3",
    spherTests = FALSE,
    spherCorrs = FALSE,
    spherCorrNone = FALSE,
    spherCorrGreenGsser = FALSE,
    spherCorrHuyFdt = FALSE,
    homoTests = FALSE,
    contrasts = NULL,
    postHoc = NULL,
    corrTukey = FALSE,
    corrScheffe = FALSE,
    corrBonf = FALSE,
    corrHolm = FALSE,
    descPlotsHAxis = NULL,
    descPlotsSepLines = NULL,
    descPlotsSepPlots = NULL,
    dispErrBars = FALSE,
    errBarDef = "ci",
    ciWidth = 95,
    dispDescStats = FALSE,
    estEffSize = FALSE,
    effSizeN2 = FALSE,
    partEffSizeN2 = FALSE,
    effSizeW2 = FALSE) {

    options <- AnovaRMOptions$new(
        rm = rm,
        rmCells = rmCells,
        bs = bs,
        cov = cov,
        rmTerms = rmTerms,
        bsTerms = bsTerms,
        ss = ss,
        spherTests = spherTests,
        spherCorrs = spherCorrs,
        spherCorrNone = spherCorrNone,
        spherCorrGreenGsser = spherCorrGreenGsser,
        spherCorrHuyFdt = spherCorrHuyFdt,
        homoTests = homoTests,
        contrasts = contrasts,
        postHoc = postHoc,
        corrTukey = corrTukey,
        corrScheffe = corrScheffe,
        corrBonf = corrBonf,
        corrHolm = corrHolm,
        descPlotsHAxis = descPlotsHAxis,
        descPlotsSepLines = descPlotsSepLines,
        descPlotsSepPlots = descPlotsSepPlots,
        dispErrBars = dispErrBars,
        errBarDef = errBarDef,
        ciWidth = ciWidth,
        dispDescStats = dispDescStats,
        estEffSize = estEffSize,
        effSizeN2 = effSizeN2,
        partEffSizeN2 = partEffSizeN2,
        effSizeW2 = effSizeW2)

    results <- AnovaRMResults$new(
        options = options)

    analysis <- AnovaRMClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
