
# This file is automatically generated, you probably don't want to edit this

ContTablesPairedOptions <- R6::R6Class(
    "ContTablesPairedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            areCounts = FALSE,
            obs = TRUE,
            pcRow = FALSE,
            pcCol = FALSE) {

            super$initialize(package='jmv', name='ContTablesPaired')
        
            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs)
            private$..areCounts <- jmvcore::OptionBool$new(
                "areCounts",
                areCounts,
                default=FALSE)
            private$..obs <- jmvcore::OptionBool$new(
                "obs",
                obs,
                default=TRUE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
        
            self$.addOption(private$..pairs)
            self$.addOption(private$..areCounts)
            self$.addOption(private$..obs)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        areCounts = function() private$..areCounts$value,
        obs = function() private$..obs$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value),
    private = list(
        ..pairs = NA,
        ..areCounts = NA,
        ..obs = NA,
        ..pcRow = NA,
        ..pcCol = NA)
)

ContTablesPairedBase <- R6::R6Class(
    "ContTablesPairedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="") {
            super$initialize(
                package = 'jmv',
                name = 'ContTablesPaired',
                version = c(1,0,0),
                options = options,
                data = data,
                datasetId = datasetId,
                analysisId = analysisId)
        }))

ContTablesPaired <- function(
    data,
    pairs,
    areCounts = FALSE,
    obs = TRUE,
    pcRow = FALSE,
    pcCol = FALSE) {

    options <- ContTablesPairedOptions$new(
        pairs = pairs,
        areCounts = areCounts,
        obs = obs,
        pcRow = pcRow,
        pcCol = pcCol)

    analysis <- ContTablesPairedClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
