
# This file is automatically generated, you probably don't want to edit this

emptyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "emptyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jmv",
                name="empty",
                requiresData=FALSE,
                ...)


        }),
    active = list(),
    private = list()
)

emptyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "emptyResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results")}))

emptyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "emptyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmv",
                name = "empty",
                version = c(1,0,0),
                options = options,
                results = emptyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

