
# This file is automatically generated, you probably don't want to edit this

FriedmanOptions <- R6::R6Class(
    "FriedmanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            measures = NULL,
            pairs = FALSE,
            desc = FALSE,
            plots = FALSE,
            plotType = "means", ...) {

            super$initialize(package='jmv', name='Friedman', ...)
        
            private$..measures <- jmvcore::OptionVariables$new(
                "measures",
                measures,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..pairs <- jmvcore::OptionBool$new(
                "pairs",
                pairs,
                default=FALSE)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..plotType <- jmvcore::OptionList$new(
                "plotType",
                plotType,
                options=list(
                    "means",
                    "medians"),
                default="means")
        
            self$.addOption(private$..measures)
            self$.addOption(private$..pairs)
            self$.addOption(private$..desc)
            self$.addOption(private$..plots)
            self$.addOption(private$..plotType)
        }),
    active = list(
        measures = function() private$..measures$value,
        pairs = function() private$..pairs$value,
        desc = function() private$..desc$value,
        plots = function() private$..plots$value,
        plotType = function() private$..plotType$value),
    private = list(
        ..measures = NA,
        ..pairs = NA,
        ..desc = NA,
        ..plots = NA,
        ..plotType = NA)
)

FriedmanResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        table = function() private$..table,
        comp = function() private$..comp,
        plot = function() private$..plot),
    private = list(
        ..table = NA,
        ..comp = NA,
        ..plot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Friedman Test")
            private$..table <- jmvcore::Table$new(
                options=options,
                name="table",
                title="Friedman Test",
                rows=1,
                clearWith=list(
                    "measures"),
                columns=list(
                    list(`name`="stat", `title`="Χ²", `type`="number"),
                    list(`name`="df", `title`="df", `type`="integer"),
                    list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue")))
            private$..comp <- jmvcore::Table$new(
                options=options,
                name="comp",
                title="Pairwise Comparisons (Durbin-Conover)",
                visible="(pairs)",
                clearWith=list(
                    "measures"),
                columns=list(
                    list(`name`="i1", `title`="", `type`="text"),
                    list(`name`="sep", `title`="", `content`="-", `type`="text", `format`="sep"),
                    list(`name`="i2", `title`="", `type`="text"),
                    list(`name`="stat", `title`="Statistic", `type`="number"),
                    list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue")))
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Descriptive Plot",
                visible="(plots)",
                renderInitFun=".plot",
                renderFun=".plot")
            self$add(private$..table)
            self$add(private$..comp)
            self$add(private$..plot)}))

FriedmanBase <- R6::R6Class(
    "FriedmanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmv',
                name = 'Friedman',
                version = c(1,0,0),
                options = options,
                results = FriedmanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

Friedman <- function(
    data,
    measures,
    pairs = FALSE,
    desc = FALSE,
    plots = FALSE,
    plotType = "means") {

    options <- FriedmanOptions$new(
        measures = measures,
        pairs = pairs,
        desc = desc,
        plots = plots,
        plotType = plotType)

    results <- FriedmanResults$new(
        options = options)

    analysis <- FriedmanClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
