
# This file is automatically generated, you probably don't want to edit this

htmlOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "htmlOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package='jmv',
                name='html',
                requiresData=FALSE,
                ...)


        }),
    active = list(),
    private = list()
)

htmlResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results")}))

htmlBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "htmlBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmv',
                name = 'html',
                version = c(1,0,0),
                options = options,
                results = htmlResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))
