
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
propTestNOptions <- R6::R6Class(
    "propTestNOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            counts = NULL,
            expected = FALSE,
            ratio = NULL, ...) {

            super$initialize(
                package='jmv',
                name='propTestN',
                requiresData=TRUE,
                ...)
        
            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "nominal",
                    "ordinal",
                    "nominaltext"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                default=NULL,
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..expected <- jmvcore::OptionBool$new(
                "expected",
                expected,
                default=FALSE)
            private$..ratio <- jmvcore::OptionArray$new(
                "ratio",
                ratio,
                template=jmvcore::OptionNumber$new(
                    "ratio",
                    NULL,
                    min=0,
                    default=1),
                default=NULL)
        
            self$.addOption(private$..var)
            self$.addOption(private$..counts)
            self$.addOption(private$..expected)
            self$.addOption(private$..ratio)
        }),
    active = list(
        var = function() private$..var$value,
        counts = function() private$..counts$value,
        expected = function() private$..expected$value,
        ratio = function() private$..ratio$value),
    private = list(
        ..var = NA,
        ..counts = NA,
        ..expected = NA,
        ..ratio = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
propTestNResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        props = function() private$..props,
        tests = function() private$..tests),
    private = list(
        ..props = NA,
        ..tests = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Proportion Test (N Outcomes)")
            private$..props <- jmvcore::Table$new(
                options=options,
                name="props",
                title="Proportions",
                rows="(levels(var))",
                clearWith=list(
                    "var",
                    "ratio",
                    "counts"),
                columns=list(
                    list(`name`="level", `title`="Level", `type`="text", `content`="($key)"),
                    list(`name`="name[obs]", `title`="", `type`="text", `content`="Observed", `visible`="(expected)"),
                    list(`name`="count[obs]", `title`="Count", `type`="integer"),
                    list(`name`="prop[obs]", `title`="Proportion", `type`="number"),
                    list(`name`="name[exp]", `title`="", `type`="text", `content`="Expected", `visible`="(expected)"),
                    list(`name`="count[exp]", `title`="Count", `type`="integer", `visible`="(expected)"),
                    list(`name`="prop[exp]", `title`="Proportion", `type`="number", `visible`="(expected)")))
            private$..tests <- jmvcore::Table$new(
                options=options,
                name="tests",
                title="\u03C7\u00B2 Goodness of Fit",
                rows=1,
                clearWith=list(
                    "var",
                    "ratio",
                    "counts"),
                columns=list(
                    list(`name`="chi", `title`="\u03C7\u00B2", `type`="number"),
                    list(`name`="df", `title`="df", `type`="integer"),
                    list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue")))
            self$add(private$..props)
            self$add(private$..tests)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
propTestNBase <- R6::R6Class(
    "propTestNBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmv',
                name = 'propTestN',
                version = c(1,0,0),
                options = options,
                results = propTestNResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE)
        }))

#' Proportion Test (N Outcomes)
#'
#' X² Goodness of fit
#'
#' @examples
#' data('HairEyeColor')
#' dat <- as.data.frame(HairEyeColor)
#' 
#' propTestN(dat, var = 'Eye', counts = 'Freq', ratio = c(1,1,1,1))
#' 
#' #
#' #  Proportion Test (N Outcomes)
#' #
#' #  Proportions
#' #  --------------------------------
#' #    Level    Count    Proportion
#' #  --------------------------------
#' #    Brown      220         0.372
#' #    Blue       215         0.363
#' #    Hazel       93         0.157
#' #    Green       64         0.108
#' #  --------------------------------
#' #
#' #
#' #  X² Goodness of Fit
#' #  -----------------------
#' #    X²     df    p
#' #  -----------------------
#' #    133     3    < .001
#' #  -----------------------
#' #
#' 
#' @param data the data as a data frame
#' @param var a string naming the variable of interest in \code{data}
#' @param counts a string naming a variable in \code{data} containing counts, 
#'   or NULL if each row represents a single observation 
#' @param expected \code{TRUE} or \code{FALSE} (default), whether expected 
#'   counts should be displayed 
#' @param ratio a vector of numbers: the expected proportions 
#' @export
propTestN <- function(
    data,
    var,
    counts = NULL,
    expected = FALSE,
    ratio = NULL) {

    options <- propTestNOptions$new(
        var = var,
        counts = counts,
        expected = expected,
        ratio = ratio)

    results <- propTestNResults$new(
        options = options)

    analysis <- propTestNClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
