
# This file is automatically generated, you probably don't want to edit this

#' @rdname jamovi
#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
#' @export
PropTestNOptions <- R6::R6Class(
    "PropTestNOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            counts = NULL, ...) {

            super$initialize(
                package='jmv',
                name='PropTestN',
                requiresData=TRUE,
                ...)
        
            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var)
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts)
        
            self$.addOption(private$..var)
            self$.addOption(private$..counts)
        }),
    active = list(
        var = function() private$..var$value,
        counts = function() private$..counts$value),
    private = list(
        ..var = NA,
        ..counts = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
PropTestNResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        props = function() private$..props,
        tests = function() private$..tests),
    private = list(
        ..props = NA,
        ..tests = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Proportion Test (N Outcomes)")
            private$..props <- jmvcore::Table$new(
                options=options,
                name="props",
                title="Proportions",
                rows="(levels(var))",
                clearWith=NULL,
                columns=list(
                    list(`name`="level", `title`="Level", `type`="text", `content`="($key)"),
                    list(`name`="count", `title`="Count", `type`="integer"),
                    list(`name`="prop", `title`="Proportion", `type`="number")))
            private$..tests <- jmvcore::Table$new(
                options=options,
                name="tests",
                title="\u03C7\u00B2 Goodness of Fit",
                rows=1,
                columns=list(
                    list(`name`="chi", `title`="\u03C7\u00B2", `type`="number"),
                    list(`name`="df", `title`="df", `type`="integer"),
                    list(`name`="p", `title`="p", `type`="number", `format`="zto,pvalue")))
            self$add(private$..props)
            self$add(private$..tests)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
PropTestNBase <- R6::R6Class(
    "PropTestNBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmv',
                name = 'PropTestN',
                version = c(1,0,0),
                options = options,
                results = PropTestNResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' PropTestN
#'
#' 
#' @param data The data set as a data frame 
#' @param var The variable of interest 
#' @param counts .
#' @export
PropTestN <- function(
    data,
    var,
    counts) {

    options <- PropTestNOptions$new(
        var = var,
        counts = counts)

    results <- PropTestNResults$new(
        options = options)

    analysis <- PropTestNClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
