
# This file is automatically generated, you probably don't want to edit this

weightsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "weightsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            weights = NULL, ...) {

            super$initialize(
                package="jmv",
                name="weights",
                requiresData=TRUE,
                ...)

            private$..weights <- jmvcore::OptionVariable$new(
                "weights",
                weights,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))

            self$.addOption(private$..weights)
        }),
    active = list(
        weights = function() private$..weights$value),
    private = list(
        ..weights = NA)
)

weightsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "weightsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Weights")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="",
                content="Data set is currently unweighted"))}))

weightsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "weightsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmv",
                name = "weights",
                version = c(1,0,0),
                options = options,
                results = weightsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

